export const FETCH_INSPIRATIONS_REQUEST = 'FETCH_INSPIRATIONS_REQUEST'
export const FETCH_INSPIRATIONS_SUCCESS = 'FETCH_INSPIRATIONS_SUCCESS'
export const FETCH_INSPIRATIONS_ERROR = 'FETCH_INSPIRATIONS_ERROR'