export const FETCH_POPULAR_EXPERIENCES_REQUEST =
  'FETCH_POPULAR_EXPERIENCES_REQUEST';
export const FETCH_POPULAR_EXPERIENCES_SUCCESS =
  'FETCH_POPULAR_EXPERIENCES_SUCCESS';
export const FETCH_POPULAR_EXPERIENCES_ERROR =
  'FETCH_POPULAR_EXPERIENCES_ERROR';
