export const FETCH_ACTIVITY_REQUEST = 'FETCH_ACTIVITY_REQUEST';
export const FETCH_ACTIVITY_SUCCESS = 'FETCH_ACTIVITY_SUCCESS';
export const FETCH_ACTIVITY_ERROR = 'FETCH_ACTIVITY_ERROR';
export const FETCH_ACTIVITY_MEDIA_REQUEST = 'FETCH_ACTIVITY_MEDIA_REQUEST';
export const FETCH_ACTIVITY_MEDIA_SUCCESS = 'FETCH_ACTIVITY_MEDIA_SUCCESS';
export const FETCH_ACTIVITY_MEDIA_ERROR = 'FETCH_ACTIVITY_MEDIA_ERROR';
