export const FETCH_AUTOCOMPLETE_REQUEST = 'FETCH_AUTOCOMPLETE_REQUEST';
export const FETCH_AUTOCOMPLETE_SUCCESS = 'FETCH_AUTOCOMPLETE_SUCCESS';
export const FETCH_AUTOCOMPLETE_ERROR = 'FETCH_AUTOCOMPLETE_ERROR';
